name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  load-config:
    name: Load Projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load project config
        id: set-matrix
        run: echo "projects=$(cat .github/workflows/projects.json | jq -c)" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.project.path }}
    needs: load-config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.load-config.outputs.projects) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ matrix.project.ballerina_version }}

      - name: Build Docker image
        working-directory: ${{ matrix.project.path }}
        run: bal build --cloud=docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        working-directory: ${{ matrix.project.path }}
        run: docker tag ${{ matrix.project.repository }}:latest docker.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.project.repository }}:${{ matrix.project.tag }}

      - name: Push Docker image
        working-directory: ${{ matrix.project.path }}
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.project.repository }}:${{ matrix.project.tag }}
