name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: config-api
      TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: 2201.12.10

      - name: Build Docker image
        working-directory: ${{ env.PROJECT_PATH }}
        run: bal build --cloud=docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        working-directory: ${{ env.PROJECT_PATH }}
        run: docker tag ${{
          env.PROJECT_PATH }}:latest docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_PATH }}:${{ env.TAG }}

      - name: Push Docker image
        working-directory: ${{ env.PROJECT_PATH }}
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_PATH }}:${{ env.TAG }}
